// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StoreService.Application.Persistence;

#nullable disable

namespace StoreService.Application.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260608102349_ReservedProducts")]
    partial class ReservedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StoreService.Domain.Entities.ProductStoreLocationEntity", b =>
                {
                    b.Property<int>("StoreLocationId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("StoreLocationId", "ProductId");

                    b.ToTable("ProductStoreLocations");
                });

            modelBuilder.Entity("StoreService.Domain.Entities.ReservedProductEntity", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("StoreLocationId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("OrderId", "StoreLocationId", "ProductId");

                    b.HasIndex("StoreLocationId")
                        .IsUnique();

                    b.ToTable("ReservedProducts");
                });

            modelBuilder.Entity("StoreService.Domain.Entities.StoreLocationEntity", b =>
                {
                    b.Property<int>("StoreLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StoreLocationId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StoreLocationId");

                    b.ToTable("StoreLocations");
                });

            modelBuilder.Entity("StoreService.Domain.Entities.ReservedProductEntity", b =>
                {
                    b.HasOne("StoreService.Domain.Entities.StoreLocationEntity", "StoreLocation")
                        .WithOne()
                        .HasForeignKey("StoreService.Domain.Entities.ReservedProductEntity", "StoreLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreLocation");
                });
#pragma warning restore 612, 618
        }
    }
}
